// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WsMessageStatus } from "./WsMessageStatus";

export interface ChatMessage {
    self_sent: boolean,
    status: WsMessageStatus,
    msg: string,
    /**
     * Also used as id.
     */
    date: number,
}