// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessage } from "./ChatMessage";

export interface StorageChat { messages: Array<ChatMessage>, nickname: string | null, receiver_onion: string, }