// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StorageChat } from "./StorageChat";

export interface StorageData { nicknames: Record<string, string>, chats: Record<string, StorageChat>, }