// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WsClientStatus } from "./WsClientStatus";

export interface WsClientUpdate { hostname: string, status: WsClientStatus, }