// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WsMessageStatus } from "./WsMessageStatus";

export interface WsMessageStatusPayload { hostname: string, status: WsMessageStatus, date: number, }